### ISSUE TITLE
Compiling problems and binary

### ISSUE THREAD

**Issue by Chusogar** [fasteddo/mcs#1]
Hi

I have tried to compile it but due to several compilation errors it isn't possible. Could you update a new version please? 

On the other hand i would like to get a binary version of mcs to be checked. Please, could you provide it?

Thanks a lot in advance and thank you so much for this interesting project!

**Comment by fasteddo** [comment]
Hello,
Sorry for such a late reply.  I was never notified that there were issues posted, so I never saw this.
There has been new commits since this was posted, so please, if you could do a fresh pull and see if you are successful.
If not, feel free to reopen with specifics.
Thanks for your interest!
